### ISSUE TITLE
Debian Support - undefined reference to `__cxa_thread_atexit'

### ISSUE THREAD

**Issue by gbedoya** [osql/osql#10]
Hi,
I attempted to compile osql on Debian 9.8 on GCP. The build fails with undefined reference to **`__cxa_thread_atexit`** Is Debian Stretch supported? Or am I using the wrong build dependencies?

**Build Details:**
cmake version 3.13.4
Package: clang-6.0 Version: 1:6.0-1 bpo9+1
Package: llvm-6.0 Version: 1:6.0-1 bpo9+1
Package: libc++-dev Version: 3.5-2
Package: libc++abi-dev Version: 3.5-2
Package: liblzma-dev Version: 5.2.2-1.2+b1

**Error:**

> remote/transports/libosquery_remote_transports_transportstls.a(tls.cpp.o): In function `osquery::getClient()':

> /home/foobar/osql/src/osquery-src/osquery/remote/transports/tls.cpp:183: undefined reference to `__cxa_thread_atexit'

> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Log:**
<img width="1100" alt="Screen Shot 2019-04-19 at 9 27 43 PM" src="https://user-images.githubusercontent.com/6805315/56461650-e4aa3d00-637b-11e9-9526-99a6a958d42b.png">

**Comment by Smjert** [comment]
Hi @gbedoya,

The issue you're encountering is due to the old version of the libc++ and libc++abi libraries Debian ships with.

A way is to compile those two libraries since it doesn't take much (beyond having to download ~100MB of LLVM source code).

Following the steps you could use:
```
cd $HOME; git clone https://github.com/llvm/llvm-project.git -b release/6.x --depth 1
cd llvm-project; mkdir build; cd build
cmake -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_CXX_COMPILER=clang++-6.0 -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" -DCMAKE_BUILD_TYPE=Release ../llvm
cmake --build . -j # // # = number of cores you want to use
sudo cmake --build . --target install-cxx
sudo cmake --build . --target install-cxxabi

// Uninstall the old libc++, eventually we will add in osql a way to specify where to look for LLVM as for macOS, so this won't be necessary

sudo apt remove libc++1 libc++-dev libc++abi1 libc++abi-dev
```

Then you need to rebuild everything, use `cmake --build . --target clean` to clean up the osql build folder, and this time it should work.

**Comment by gbedoya** [comment]
Build success. Thanks.
