### ISSUE TITLE
YARA supported version / modules

### ISSUE THREAD

**Issue by Neo23x0** [osql/osql#11]
Hi, I am interested in the YARA support within osquery/osql 

Can anyone tell me, which YARA version is built into the endpoint component and which modules does it support? (e.g. with OpenSSL enabled features using `--with-crypto`)

I maintain a list of products and their YARA support and would like to know how this is done in osquery/osql.
https://github.com/NextronSystems/valhallaAPI/blob/master/valhallaAPI/filters.py#L6

Thanks

**Comment by Neo23x0** [comment]
Ah, I can at least see that YARA version 3.7.1 is used. 
https://github.com/osql/osql/blob/master/third-party/yara/CMakeLists.txt#L19

**Comment by alessandrogario** [comment]
Hello @Neo23x0,

Libraries are built using *brew (macOS and Linux) and Chocolatey. You can find the formula scripts in the upstream repository (osquery is imported as a submodule) under `tools/provision`.

The Linux and macOS script that builds Yara can be found here: https://github.com/facebook/osquery/blob/experimental/tools/provision/formula/yara.rb

**Comment by Neo23x0** [comment]
Ah, great! 
I can see from the dependencies that OpenSSL is a requirement, correct?
This is important than OpenSSL enables some important features like the "hash" and certain functions of the "pe" module of YARA, like e.g. "pe.imphash". 

Thanks for pointing me to the right build script.
