### ISSUE TITLE
drop support for asl table on macOS

### ISSUE THREAD

**Issue by groob** [osql/osql#13]
ASL logging is deprecating on macOS, which keeps the osquery builds from moving to a newer darwin SDK.

Suggestion: move the asl table out of core into an extension. Move to the 10.14 SDK

**Comment by keeleysam** [comment]
it should be replaced with something that calls https://developer.apple.com/documentation/logging/oslogstore/3204125-getentries which is new in 10.15

**Comment by mike-myers-tob** [comment]
Opened upstream: https://github.com/osquery/osquery/issues/5760
