### ISSUE TITLE
Fix ProcessOpenFilesTest test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#16]
This test is runs on Linux and macOS, fails on both:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:
[processopenfilestest-linux.log](https://github.com/osql/osql/files/3242142/processopenfilestest-linux.log)

CI log macOS:
[processopenfilestest-macos.log](https://github.com/osql/osql/files/3242146/processopenfilestest-macos.log)

# Task

Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to work now on upstream CI if we can close this issue.
- Linux: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=734&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3513&lineEnd=3513&colStart=30&colEnd=46
- macOS: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=734&view=logs&jobId=600a1784-03bb-5433-95da-af5cec3fba26&taskId=485d5b03-6be8-53e7-4d6e-0773d4a542a9&lineStart=3463&lineEnd=3463&colStart=30&colEnd=46
