### ISSUE TITLE
Fix ProgramsTest test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#17]
This test runs on Linux and macOS, fails on both:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:
> 4: [ RUN      ] ProgramsTest.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/programs.cpp:22: Failure
> 4: Expected: (data.size()) > (0ul), actual: 0 vs 0
> 4: [  FAILED  ] ProgramsTest.test_sanity (0 ms)

CI log macOS:
> 4: [ RUN      ] ProgramsTest.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/programs.cpp:22: Failure
> 4: Expected: (data.size()) > (0ul), actual: 0 vs 0
> 4: [  FAILED  ] ProgramsTest.test_sanity (0 ms)

# Task
Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
`programs` is a Windows-specific virtual table: https://osquery.io/schema/3.3.2#programs so it doesn't get tested on Linux or macOS, does it?
