### ISSUE TITLE
Fix InterfaceDetailsTest.sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#18]
This test runs on all platforms, fails on Windows and Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] InterfaceDetailsTest.sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:112: Failure
> 4: Expected: (validation_map.count(rec.first)) != (std::size_t{0}), actual: 0 vs 0
> 4: Unexpected column "pci_slot" in a row
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "last_change" with value "-1" failed
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:112: Failure
> 4: Expected: (validation_map.count(rec.first)) != (std::size_t{0}), actual: 0 vs 0
> 4: Unexpected column "pci_slot" in a row
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "last_change" with value "-1" failed
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:112: Failure
> 4: Expected: (validation_map.count(rec.first)) != (std::size_t{0}), actual: 0 vs 0
> 4: Unexpected column "pci_slot" in a row
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "last_change" with value "-1" failed
> 4: [  FAILED  ] InterfaceDetailsTest.sanity (1 ms)

CI log Windows:

> 4: [ RUN      ] InterfaceDetailsTest.sanity
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "collisions" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "odrops" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "mac" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "odrops" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "odrops" with value "" failed
> 4: [  FAILED  ] InterfaceDetailsTest.sanity (269 ms)

# Task
Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
It's working in the upstream CI if we want to close this issue:
- Linux: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=734&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3160&lineEnd=3160&colStart=18&colEnd=50
- Windows: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=734&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=2497&lineEnd=2497&colStart=30&colEnd=50
