### ISSUE TITLE
Fix KernelInfo.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#19]
This test runs on all platforms, fails on Windows and Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] KernelInfo.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "device" with value "UUID=68e226b2-aa5a-4379-8391-55dade9bdeb0" failed
> 4: [  FAILED  ] KernelInfo.test_sanity (1 ms)

CI log Windows:

> 4: [ RUN      ] KernelInfo.test_sanity
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "device" with value "\\\\?\\Volume{c94ef899-0000-0000-0000-501f00000000}\\" failed
> 4: [  FAILED  ] KernelInfo.test_sanity (2 ms)

# Task
Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
Can we close this issue? It's passing in the upstream CI:
- Linux: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3661&lineEnd=3661&colStart=18&colEnd=40
- Windows: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=2702&lineEnd=2702&colStart=30&colEnd=38
