### ISSUE TITLE
Fix OsVersion.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#20]
This test runs on all platforms, fails on Windows and Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] OsVersion.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "build" with value "" failed
> 4: [  FAILED  ] OsVersion.test_sanity (0 ms)

CI log Windows:

> 4: [ RUN      ] OsVersion.test_sanity
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(112): error: Expected: (validation_map.count(rec.first)) != (std::size_t{0}), actual: 0 vs 0
> 4: Unexpected column "install_date" in a row
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "patch" with value "" failed
> 4: [  FAILED  ] OsVersion.test_sanity (7 ms)

# Task
Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
Any idea why this fix was necessary here, but the unfixed test still passes in the upstream osquery?

https://github.com/osquery/osquery/blob/e6fe15eb49660725e65dba1549932ed96e0a8c6e/tests/integration/tables/os_version.cpp versus your change https://github.com/Smjert/osql/commit/e2a676fdb00c203b6fe4930fcb5e01f8ba4c6b23

Passing in the upstream CI: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=600a1784-03bb-5433-95da-af5cec3fba26&taskId=485d5b03-6be8-53e7-4d6e-0773d4a542a9&lineStart=3127&lineEnd=3127&colStart=18&colEnd=39
