### ISSUE TITLE
Fix RoutesTest.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#21]
This test runs on all platforms, fails on Windows and macOS:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log macOS:

> 4: [ RUN      ] RoutesTest.test_sanity
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "gateway" with value "link#1" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "gateway" with value "link#7" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "static" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:129: Failure
> 4: Value of: boost::get<CustomCheckerType>(validator)(value)
> 4:   Actual: false
> 4: Expected: true
> 4: Custom validator of the column "type" with value "router" failed
> 4: [  FAILED  ] RoutesTest.test_sanity (7 ms)

CI log Windows:

> 4: [ RUN      ] RoutesTest.test_sanity
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "flags" with value "-1" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(125): error: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "interface" with value "" failed
> 4: [  FAILED  ] RoutesTest.test_sanity (3 ms)

# Task

Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
Works upstream, close this?

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=2577&lineEnd=2577&colStart=30&colEnd=36
