### ISSUE TITLE
Fix RegistryTest.sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#22]
This test runs on Linux and macOS, fails on both:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] RegistryTest.sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/registry.cpp:24: Failure
> 4: Expected: (rows.size()) > (0ul), actual: 0 vs 0
> 4: [  FAILED  ] RegistryTest.sanity (0 ms)

CI log macOS:

> 4: [ RUN      ] RegistryTest.sanity
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/registry.cpp:24: Failure
> 4: Expected: (rows.size()) > (0ul), actual: 0 vs 0
> 4: [  FAILED  ] RegistryTest.sanity (0 ms)

# Task
Fix the test on all platforms and re-enable it.

**Comment by mike-myers-tob** [comment]
It seems like this was a Windows-only test, was it even supposed to be running on Linux and macOS?

In the upstream CI it is successfully running on Windows, and not being run/tested on Linux.

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=2753&lineEnd=2753&colStart=18&colEnd=42
