### ISSUE TITLE
Fix TLSConfigTests.test_retrieve_config test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#23]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSConfigTests.test_retrieve_config
> 2: d:\a\1\s\osquery\config\plugins\tests\tls_config_tests.cpp(89): error: Expected equality of these values:
> 2:   "6f1980704cb3fd0c902a8a1107f65c59016c5dd2"
> 2:   c.getHash("tls_plugin")
> 2:     Which is: ""
> 2: WARNING: Logging before InitGoogleLogging() is written to STDERR
> 2: W0530 22:09:32.556301  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:33.728251  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:34.771811  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: E0530 22:09:35.815351  4612 config.cpp:774] updateSource failed to parse config, of source: awesome and content: 
> 2: W0530 22:09:35.815351  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:36.852073  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:37.886142  4612 options.cpp:94] Cannot set unknown or invalid flag: fake
> 2: W0530 22:09:37.886142  4612 options.cpp:94] Cannot set unknown or invalid flag: fake_custom_fake
> 2: W0530 22:09:37.886142  4612 options.cpp:94] Cannot set unknown or invalid flag: fake
> 2: W0530 22:09:37.886142  4612 options.cpp:94] Cannot set unknown or invalid flag: fake_custom_fake
> 2: W0530 22:09:37.886142  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:37.886142  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:38.918941  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:38.918941  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:39.959376  4612 decorators.cpp:196] Invalid decorator interval rate 61 in config source: awesome
> 2: W0530 22:09:46.133448  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:09:52.267220  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:10:06.479496  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:10:12.617614  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:10:31.936806  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:10:38.038128  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:00.325760  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:06.446219  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:24.727663  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:30.864043  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:45.104351  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:11:51.192847  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:12:10.454933  4612 tls_enroll.cpp:67] Failed enrollment request to https://localhost:24147/enroll (Request error: Failed to connect to localhost:24147: unknown error) retrying...
> 2: W0530 22:12:16.5723d:\a\1\s\osquery\config\plugins\tests\tls_config_tests.cpp(97): error: Value of: status.ok()
> 2:   Actual: false
> 2: Expected: true
> 2: [  FAILED  ] TLSConfigTests.test_retrieve_config (197172 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Tracking this upstream here: https://github.com/osquery/osquery/issues/5768
