### ISSUE TITLE
Fix TLSConfigTests.test_setup test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#24]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSConfigTests.test_setup
> 2: d:\a\1\s\osquery\config\plugins\tests\tls_config_tests.cpp(150): error: Value of: status.ok()
> 2:   Actual: false
> 2: Expected: true
> 2: [  FAILED  ] TLSConfigTests.test_setup (4041 ms)

# Task

Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Tracking this upstream here: https://github.com/osquery/osquery/issues/5768
