### ISSUE TITLE
Fix DistributedTests.test_workflow test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#25]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] DistributedTests.test_workflow
> 2: d:\a\1\s\osquery\distributed\tests\distributed_tests.cpp(186): error: Value of: s.ok()
> 2:   Actual: false
> 2: Expected: true
> 2: d:\a\1\s\osquery\distributed\tests\distributed_tests.cpp(187): error: Expected equality of these values:
> 2:   s.toString()
> 2:     Which is: "Error Parsing JSON"
> 2:   "OK"
> 2: d:\a\1\s\osquery\distributed\tests\distributed_tests.cpp(189): error: Expected equality of these values:
> 2:   dist.getPendingQueryCount()
> 2:     Which is: 0
> 2:   2U
> 2:     Which is: 2
> 2: [  FAILED  ] DistributedTests.test_workflow (118904 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working in the upstream CI: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=582&lineEnd=582&colStart=25&colEnd=36

Can we close this issue?
