### ISSUE TITLE
Fix TLSEnrollTests.test_tls_enroll test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#26]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSEnrollTests.test_tls_enroll
> 2: d:\a\1\s\osquery\remote\enroll\plugins\tests\tls_enroll_tests.cpp(76): error: Value of: status.ok()
> 2:   Actual: false
> 2: Expected: true
> 2: d:\a\1\s\osquery\remote\enroll\plugins\tests\tls_enroll_tests.cpp(77): error: Expected equality of these values:
> 2:   response.doc().Size()
> 2:     Which is: 0
> 2:   1U
> 2:     Which is: 1
> 2: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
> 2: [  FAILED  ] TLSEnrollTests.test_tls_enroll (24425 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
I think these tests were moved upstream, to https://github.com/osquery/osquery/blob/master/osquery/remote/enroll/tests/enroll_tests.cpp 

They seem to be passing: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=856&lineEnd=856&colStart=32&colEnd=38

We can close this issue?
