### ISSUE TITLE
Fix TLSTransportsTests.test_call_with_params test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#27]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSTransportsTests.test_call_with_params
> 2: d:\a\1\s\osquery\remote\transports\tests\tls_transports_tests.cpp(115): error: Expected equality of these values:
> 2:   params.doc()
> 2:     Which is: 104-byte object <01-00 00-00 00-00 00-00 10-00 00-00 00-00 00-00 C8-EB A1-54 FF-01 03-00 70-03 AB-54 FF-01 00-00 70-03 AB-54 FF-01 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-04 00-00 00-00 00-00 00-00 00-00 FC-7F 00-00 00-00 00-00 00-00 00-00>
> 2:   recv.doc()
> 2:     Which is: 104-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 03-00 B0-FF AA-54 FF-01 00-00 B0-FF AA-54 FF-01 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-04 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
> 2: [  FAILED  ] TLSTransportsTests.test_call_with_params (4051 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Tracking this upstream here: https://github.com/osquery/osquery/issues/5768
