### ISSUE TITLE
Fix TLSTransportsTests.test_call_verify_peer test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#28]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSTransportsTests.test_call_verify_peer
> 2: d:\a\1\s\osquery\remote\transports\tests\tls_transports_tests.cpp(135): error: Expected equality of these values:
> 2:   status.getMessage()
> 2:     Which is: "Request error: Failed to connect to localhost:20554: unknown error"
> 2:   "Request error: certificate verify failed"
> 2: [  FAILED  ] TLSTransportsTests.test_call_verify_peer (4070 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Tracking this upstream here: https://github.com/osquery/osquery/issues/5768
