### ISSUE TITLE
Fix TLSTransportsTests.test_call_client_auth test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#30]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 2: [ RUN      ] TLSTransportsTests.test_call_client_auth
> 2: d:\a\1\s\osquery\remote\transports\tests\tls_transports_tests.cpp(178): error: Value of: status.ok()
> 2:   Actual: false
> 2: Expected: true
> 2: [  FAILED  ] TLSTransportsTests.test_call_client_auth (4076 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Tracking this upstream here: https://github.com/osquery/osquery/issues/5768
