### ISSUE TITLE
Fix NetworkingTablesTests.test_listening_ports test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#31]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 3: [ RUN      ] NetworkingTablesTests.test_listening_ports
> 3: d:\a\1\s\osquery\tables\networking\tests\networking_tables_tests.cpp(68): error: Expected: (pid.size()) > (0U), actual: 0 vs 0
> 3: [  FAILED  ] NetworkingTablesTests.test_listening_ports (2 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working in the upstream CI: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=650&lineEnd=650&colStart=49&colEnd=65

Can we close this issue?
