### ISSUE TITLE
Fix SystemsTablesTests.test_abstract_joins test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#32]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 3: [ RUN      ] SystemsTablesTests.test_abstract_joins
> 3: d:\a\1\s\osquery\tables\system\tests\system_tables_tests.cpp(194): error: Expected: (results.rows().size()) > (1U), actual: 0 vs 1
> 3: [  FAILED  ] SystemsTablesTests.test_abstract_joins (242 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working in the upstream CI: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=771&lineEnd=771&colStart=42&colEnd=56 

Can we close this issue?
