### ISSUE TITLE
Fix Time.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#34]
This test runs on all platforms, fails on Windows:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> 4: [ RUN      ] Time.test_sanity
> 4: d:\a\1\s\osquery\tests\integration\tables\helper.cpp(112): error: Expected: (validation_map.count(rec.first)) != (std::size_t{0}), actual: 0 vs 0
> 4: Unexpected column "win_timestamp" in a row
> 4: [  FAILED  ] Time.test_sanity (0 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
This is working in the upstream CI, if we can close this issue: https://dev.azure.com/trailofbits/osquery/_build/results?buildId=738&view=logs&jobId=acefc29f-3256-5fff-5f4b-77e5e3dc5221&taskId=90db1820-c920-55a9-6e5f-47111b35f008&lineStart=2588&lineEnd=2588&colStart=18&colEnd=34
