### ISSUE TITLE
Fix test_windows_service.py test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#35]
This test runs only on Windows and fails:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Windows:

> test 7
>     Start 7: python_test_windows_service
> 
> 7: Test command: C:\hostedtoolcache\windows\Python\2.7.16\x64\python.exe "D:/a/1/s/tools/tests/test_windows_service.py" "--verbose" "--build" "D:/a/1/s/build"
> 7: Test timeout computed to be: 9.99988e+06
> 7/7 Test #7: python_test_windows_service ......***Failed    0.21 sec

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Any idea what happened to this test? I can't find it.
