### ISSUE TITLE
Fix AptSourcesTest.sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#36]
This test runs on Linux and macOS, fails only on Linux on Ubuntu 16.04:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] AptSourcesTest.sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "version" with value "" failed
> 4: [  FAILED  ] AptSourcesTest.sanity (37 ms)

# Task
Fix the test and re-enable it.
Maybe also evaluate if it makes sense that is run on macOS too.

**Comment by mike-myers-tob** [comment]
Closing since some packages may not have a version filled out, and this test is not testing something useful.
