### ISSUE TITLE
Fix ProcessEnvs.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#38]
This test runs on Linux and macOS, fails only on Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] ProcessEnvs.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/process_envs.cpp:60: Failure
> 4: Expected: (std::find(data.begin(), data.end(), r)) != (data.end()), actual: 8-byte object <D8-73 E7-4D BB-55 00-00> vs 8-byte object <D8-73 E7-4D BB-55 00-00>
> 4: Test env variable not found
> 4: [  FAILED  ] ProcessEnvs.test_sanity (4 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working okay now in the upstream CI? Can we close this?

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3517&lineEnd=3517&colStart=30&colEnd=41
