### ISSUE TITLE
Fix SystemControlsTest.sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#39]
This test runs on Linux and macOS, fails only on Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log on Linux:
[systemcontrolstest-sanity-linux.log](https://github.com/osql/osql/files/3242413/systemcontrolstest-sanity-linux.log)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working okay in Azure Pipelines now? Can we close this?

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3564&lineEnd=3564&colStart=30&colEnd=48
