### ISSUE TITLE
Fix SystemInfo.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#40]
This test runs on all platforms, fails only on Linux:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log Linux:

> 4: [ RUN      ] SystemInfo.test_sanity
> 4: /home/vsts/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "hardware_serial" with value "" failed
> 4: [  FAILED  ] SystemInfo.test_sanity (11 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Seems to be working fine in Azure Pipelines now? Can we close this?

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=733&view=logs&jobId=70c7356e-0f98-5371-69fa-6cc33513ad22&taskId=7660dc51-9b78-53b4-88f5-f7966dc23c57&lineStart=3258&lineEnd=3258&colStart=30&colEnd=40
