### ISSUE TITLE
Fix UserGroups.test_sanity test failing on the CI

### ISSUE THREAD

**Issue by Smjert** [osql/osql#41]
This test runs on all platforms, fails only on macOS:
https://dev.azure.com/trailofbits/osql/_build/results?buildId=258

CI log macOS:

> 4: [ RUN      ] UserGroups.test_sanity
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "gid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "uid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "uid" with value "-2" failed
> 4: /Users/vsts/agent/2.150.3/work/1/s/osquery/tests/integration/tables/helper.cpp:125: Failure
> 4: Value of: validate_value_using_flags(value, flags)
> 4:   Actual: false
> 4: Expected: true
> 4: Standard validator of the column "uid" with value "-2" failed
> 4: [  FAILED  ] UserGroups.test_sanity (335 ms)

# Task
Fix the test and re-enable it.

**Comment by mike-myers-tob** [comment]
Works on the CI upstream, if we can close the issue here.

https://dev.azure.com/trailofbits/osquery/_build/results?buildId=734&view=logs&jobId=600a1784-03bb-5433-95da-af5cec3fba26&taskId=485d5b03-6be8-53e7-4d6e-0773d4a542a9&lineStart=3211&lineEnd=3211&colStart=18&colEnd=29
