### ISSUE TITLE
Migrate 3rd party libraries to a writable repository

### ISSUE THREAD

**Issue by alessandrogario** [osql/osql#43]
The build process relies on homebrew and linuxbrew to package dependencies. It is currently not possible to update the bottles since that would require write access to the S3 bucket used as repository.

**Comment by mike-myers-tob** [comment]
Why is the dependent package being cached as a binary in an S3 bucket? Just to save on build time? Is it a choice by the original osquery repo maintainers, or a choice of the package maintainers? Can we not force a build using the `--build-from-source` parameter to Homebrew?

@woodruffw your experience might be helpful here. What's the recommended way for a build to depend on a package?

**Comment by alessandrogario** [comment]
Homebrew will already build from source whenever the binary bottle is not ready. The reason to have the bottles is to save time and make sure we always link again the exact same version

**Comment by woodruffw** [comment]
Yep, what Alessandro said. We could remove the binaries entirely, but that would require each contributor to build the (fairly hefty) dependencies on their own.

I think all we really need to do here is replace Facebook's S3 bucket with our own binary repository. JFrog's Artifactory has served the Homebrew project well enough (and there's already mature tooling in place for it), but just about anything (including a different S3 bucket that the osql community maintains) will work.
