### ISSUE TITLE
MacOS signature.hash_resources column

### ISSUE THREAD

**Issue by packetzero** [osql/osql#67]
Looking at the implementation of the MacOS signature table, there is a column called 'hash_resources' .  I believe this is to allow for queries without calculating hash of application resource directory.  The column is not marked as an INDEX or ADDITIONAL.  With the bug in osql for communicating index constraints to sqlite, the table generate() still gets the constraint values for this column.  However, when the bug is fixed, the signature generate() will not receive the value.

Other tables solve this by checking whether certain columns are requested.  For example, if cdhash column is not requested, then don't hash the resources.  Hiding or phasing out the hash_resources column and checking for cdhash in requested columns would be my recommendation.  Alternatively, add the ADDITIONAL option on the hash_resources column.

**Comment by zwass** [comment]
@packetzero you'll want to take a look at the discussion that led to that code: https://github.com/facebook/osquery/issues/2987

IIRC it toggles an option but either way values should be generated by those columns.

**Comment by packetzero** [comment]
Thanks Zach

**Comment by packetzero** [comment]
Looks like this is not about removing an unused column.  It's about not hashing resources folder.  The hash is still computed.  Closing ticket...
