### ISSUE TITLE
license info in files

### ISSUE THREAD

**Issue by jlovejoy** [osql/osql#71]
I noticed you use the SPDX license identifier in your README https://github.com/osql/osql/blob/5188ce5288abe0e323b8e8bd364f452134a62d00/LICENSE
But in the files, it looks like you are using a more word-y header:
" *  This source code is licensed under both the Apache 2.0 license (found in the
 *  LICENSE file in the root directory of this source tree) and the GPLv2 (found
 *  in the COPYING file in the root directory of this source tree).
 *  You may select, at your option, one of the above-listed licenses."

Did you now you can simply use the SPDX identifier in the source files too? This is easier for machines to read (and humans) and used by lots of other projects! See more info here: https://spdx.org/ids

:)

**Comment by directionless** [comment]
Thanks for the note! As https://github.com/osquery/osquery/ is now community run, the osql project is, I believe, deprecated.
